// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SqliteTool.Migrations
{
    [DbContext(typeof(DiabloContext))]
    partial class DiabloContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.15");

            modelBuilder.Entity("SqlLiteTool.Models.Act", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DiabloActsid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("DiabloActsid");

                    b.ToTable("Act");
                });

            modelBuilder.Entity("SqlLiteTool.Models.DiabloActs", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("DiabloActs");
                });

            modelBuilder.Entity("SqlLiteTool.Models.Quest", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Actid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("Actid");

                    b.ToTable("Quest");
                });

            modelBuilder.Entity("SqlLiteTool.Models.Act", b =>
                {
                    b.HasOne("SqlLiteTool.Models.DiabloActs", null)
                        .WithMany("acts")
                        .HasForeignKey("DiabloActsid");
                });

            modelBuilder.Entity("SqlLiteTool.Models.Quest", b =>
                {
                    b.HasOne("SqlLiteTool.Models.Act", null)
                        .WithMany("quests")
                        .HasForeignKey("Actid");
                });

            modelBuilder.Entity("SqlLiteTool.Models.Act", b =>
                {
                    b.Navigation("quests");
                });

            modelBuilder.Entity("SqlLiteTool.Models.DiabloActs", b =>
                {
                    b.Navigation("acts");
                });
#pragma warning restore 612, 618
        }
    }
}
