// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SqlLiteTools.Migrations
{
    [DbContext(typeof(DiabloContext))]
    [Migration("20240211200621_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.15");

            modelBuilder.Entity("DomaineLayer.Model.Act", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DiabloActsid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("DiabloActsid");

                    b.ToTable("Act", (string)null);
                });

            modelBuilder.Entity("DomaineLayer.Model.DiabloActs", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("DiabloActs");
                });

            modelBuilder.Entity("DomaineLayer.Model.Quest", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Actid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("Actid");

                    b.ToTable("Quest");
                });

            modelBuilder.Entity("DomaineLayer.Model.Act", b =>
                {
                    b.HasOne("DomaineLayer.Model.DiabloActs", null)
                        .WithMany("acts")
                        .HasForeignKey("DiabloActsid");
                });

            modelBuilder.Entity("DomaineLayer.Model.Quest", b =>
                {
                    b.HasOne("DomaineLayer.Model.Act", null)
                        .WithMany("quests")
                        .HasForeignKey("Actid");
                });

            modelBuilder.Entity("DomaineLayer.Model.Act", b =>
                {
                    b.Navigation("quests");
                });

            modelBuilder.Entity("DomaineLayer.Model.DiabloActs", b =>
                {
                    b.Navigation("acts");
                });
#pragma warning restore 612, 618
        }
    }
}
